<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="ChaoQun Shi" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>Project 2: Modeling, Testing, and Predicting</title>
    <meta name="generator" content="Hugo 0.83.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project2/">Project 2: Modeling, Testing, and Predicting</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="modeling" class="section level1">
<h1>Modeling</h1>
<div id="chaoqun-shi-eidcs59386" class="section level2">
<h2>Chaoqun Shi EID:CS59386</h2>
</div>
<div id="instructions" class="section level2">
<h2>Instructions</h2>
<p>A knitted R Markdown document (preferably HTML) and the raw R Markdown file (as .Rmd) should both be submitted to Canvas by 11:59pm on the due date. These two documents will be graded jointly, so they must be consistent (i.e., don’t change the R Markdown file without also updating the knitted document). In the .Rmd file for Project 2, you can copy the first code-chunk into your project .Rmd file to get better formatting. Notice that you can adjust the opts_chunk$set(…) above to set certain parameters if necessary to make the knitting cleaner (you can globally set the size of all plots, etc). You can copy the set-up chunk in Project2.Rmd: I have gone ahead and set a few for you (such as disabling warnings and package-loading messges when knitting)!</p>
<p>Like before, I envision your written text forming something of a narrative structure around your code/output. All results presented must have corresponding code. Any answers/results/plots etc. given without the corresponding R code that generated the result will not be graded. Furthermore, all code contained in our project document should work properly. Please do not include any extraneous code or code which produces error messages. (Code which produces warnings is fine as long as you understand what the warnings mean.)</p>
</div>
<div id="find-data" class="section level2">
<h2>Find data:</h2>
<p>Find one dataset with at least 5 variables (ideally more!) that you want to use to build models/test hypotheses. At least one should be categorical (with 2-5 groups, ideally; definitely fewer than 10) and at least two should be numeric (taking on more than 10 distinct values). Ideally, at least of your variables will be binary (if not, you will have to create one by discretizing a numeric or collapsing levels of a categorical). You will need a minimum of 40 observations (<em>at least</em> 10 observations for every explanatory variable you have, ideally 20+ observations/variable).</p>
<p>It is perfectly fine to use either dataset (or the merged dataset, or a subset of your variables) from Project 1. However, I might encourage you to diversify things a bit and choose a different dataset to work with (particularly if the variables did not reveal interesting associations in Project 1 that you want to follow up with). The only requirement/restriction is that you may not use data from any examples we have done in class or lab. It would be a good idea to pick more cohesive data this time around (i.e., variables that you actually thing might have a relationship you would want to test). Think more along the lines of your Biostats project.</p>
<p>Again, you can use data from anywhere you want (see bottom for resources)! If you want a quick way to see whether a built-in (R) dataset has binary and/or character (i.e., categorical) variables, check out this list: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
</div>
<div id="guidelines-and-rubric" class="section level2">
<h2>Guidelines and Rubric</h2>
<ul>
<li><strong>0. (5 pts)</strong> Introduce your dataset and each of your variables (or just your main variables if you have lots) in a paragraph. What are they measuring? How many observations?</li>
</ul>
<pre class="r"><code>birthwt &lt;- readr::read_csv(&#39;birthwt.csv&#39;)
birthwt %&gt;% glimpse()</code></pre>
<pre><code>## Rows: 188
## Columns: 9
## $ age &lt;dbl&gt; 19, 33, 20, 21, 18, 21, 22, 17, 29, 26, 19,
19, 22, 30, 18, 18, 15, 25, 20, 28, 32,…
## $ lwt &lt;dbl&gt; 182, 155, 105, 108, 107, 124, 118, 103, 123,
113, 95, 150, 95, 107, 100, 100, 98, 1…
## $ race &lt;chr&gt; &quot;black&quot;, &quot;other&quot;, &quot;white&quot;, &quot;white&quot;,
&quot;white&quot;, &quot;other&quot;, &quot;white&quot;, &quot;other&quot;, &quot;white&quot;, &quot;w…
## $ smoke &lt;chr&gt; &quot;no&quot;, &quot;no&quot;, &quot;yes&quot;, &quot;yes&quot;, &quot;yes&quot;, &quot;no&quot;,
&quot;no&quot;, &quot;no&quot;, &quot;yes&quot;, &quot;yes&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, …
## $ ptl &lt;chr&gt; &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;,
&quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;yes&quot;…
## $ ht &lt;chr&gt; &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;,
&quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;yes&quot;, &quot;no&quot;…
## $ ui &lt;chr&gt; &quot;yes&quot;, &quot;no&quot;, &quot;no&quot;, &quot;yes&quot;, &quot;yes&quot;, &quot;no&quot;, &quot;no&quot;,
&quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;y…
## $ ftv &lt;chr&gt; &quot;none&quot;, &quot;two or more&quot;, &quot;one&quot;, &quot;two or more&quot;,
&quot;none&quot;, &quot;none&quot;, &quot;one&quot;, &quot;one&quot;, &quot;one&quot;, &quot;…
## $ bwt &lt;dbl&gt; 2523, 2551, 2557, 2594, 2600, 2622, 2637,
2637, 2663, 2665, 2722, 2733, 2751, 2750,…</code></pre>
<p><em>The data came from a study that examined the risk factors associated with low birth weight.Low birth weight is closely linked to childbirth and later health.In 1986, researchers took various measurements on a group of pregnant women at Baystate Medical Center in Springfield, Massachusetts.</em></p>
<p><em>age: The mother’s age when the child was born.</em></p>
<p><em>lwt: The mother’s weight (lbs) just prior to pregnancy.</em></p>
<p><em>race: Race of the mother.</em></p>
<p><em>smoke: Did the mother smoke during pregnancy? </em></p>
<p><em>ptl : Has the mother had previous premature labors? </em></p>
<p><em>ht: Does the mother have a history of hypertension?</em></p>
<p><em>ui : Was urinary irritation present during pregnancy?</em></p>
<p><em>ftv : The number of doctor visits before birth.</em></p>
<p><em>bwt : The child’s weight (g).</em></p>
<ul>
<li><strong>1. (15 pts)</strong> Perform a MANOVA testing whether any of your numeric variables (or a subset of them, if including them all is unreasonable or doesn’t make sense) show a mean difference across levels of one of your categorical variables (3). If they do, perform univariate ANOVAs to find response(s) showing a mean difference across groups (3), and perform post-hoc t tests to find which groups differ (3). Discuss the number of tests you have performed, calculate the probability of at least one type I error (if unadjusted), and adjust the significance level accordingly (bonferroni correction) before discussing significant differences (3). Briefly discuss some of the MANOVA assumptions and whether or not they are likely to have been met here (no need for anything too in-depth) (2).</li>
</ul>
<pre class="r"><code>man1 &lt;- manova(cbind(lwt,bwt)~race, data=birthwt)
summary(man1)</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## race 2 0.14334 7.1411 4 370 1.511e-05 ***
## Residuals 185
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(man1)</code></pre>
<pre><code>## Response lwt :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## race 2 14427 7213.5 8.2697 0.0003631 ***
## Residuals 185 161372 872.3
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response bwt :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## race 2 5675025 2837512 5.7957 0.00362 **
## Residuals 185 90574761 489593
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>pairwise.t.test(birthwt$lwt,birthwt$race, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  birthwt$lwt and birthwt$race 
## 
##       black   other  
## other 0.00012 -      
## white 0.02537 0.01129
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(birthwt$bwt,birthwt$race, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  birthwt$bwt and birthwt$race 
## 
##       black  other 
## other 0.5972 -     
## white 0.0097 0.0047
## 
## P value adjustment method: none</code></pre>
<p><em>From manova We can see overall MANOVA is significant, so we perform follow-up ANOVAs foreach variable, and they both significant: For bwt and lwt, at least one race differs.Then perform t test, bwt is more significant.</em></p>
<p><em>We did 1 MANOVA, 2 ANOVAs, and 6 t tests. probability of at least one type I error is 1-0.95^9 = 0.3698. To keep Type I error rate (FWER) at .05, set α=0.05/9=0.0056.</em></p>
<ul>
<li><strong>2. (10 pts)</strong> Perform some kind of randomization test on your data (that makes sense). The statistic can be anything you want (mean difference, correlation, F-statistic/ANOVA, chi-squared), etc. State null and alternative hypotheses, perform the test, and interpret the results (7). Create a plot visualizing the null distribution and the test statistic (3).</li>
</ul>
<pre class="r"><code>library(vegan)
dists &lt;- birthwt%&gt;%select(lwt, bwt) %&gt;% dist()
adonis(dists~race,data=birthwt)</code></pre>
<pre><code>##
## Call:
## adonis(formula = dists ~ race, data = birthwt)
##
## Permutation: free
## Number of permutations: 999
##
## Terms added sequentially (first to last)
##
## Df SumsOfSqs MeanSqs F.Model R2 Pr(&gt;F)
## race 2 5689452 2844726 5.8001 0.059 0.007 **
## Residuals 185 90736133 490466 0.941
## Total 187 96425584 1.000
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>birthwt%&gt;%select(race,lwt,bwt)%&gt;%pivot_longer(-1,names_to=&#39;DV&#39;, values_to=&#39;measure&#39;)%&gt;%
  ggplot(aes(race,measure,fill=race))+geom_bar(stat=&quot;summary&quot;)+geom_errorbar(stat=&quot;summary&quot;, width=.5)+
  facet_wrap(~DV, nrow=2)+coord_flip()+ylab(&quot;&quot;)+theme(legend.position = &quot;none&quot;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-3-1.png" width="768" style="display: block; margin: auto;" /></p>
<p><em>From the plot bwt is more different across races.</em></p>
<ul>
<li><p><strong>3. (40 pts)</strong> Build a linear regression model predicting one of your response variables from at least 2 other variables, including their interaction. Mean-center any numeric variables involved in the interaction.</p>
<ul>
<li>Interpret the coefficient estimates (do not discuss significance) (10)</li>
</ul></li>
</ul>
<pre class="r"><code>birthwt$lwt_c &lt;- birthwt$lwt - mean(birthwt$lwt)
fit&lt;-lm(bwt ~ smoke*lwt_c, data = birthwt)
summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = bwt ~ smoke * lwt_c, data = birthwt)
##
## Residuals:
## Min 1Q Median 3Q Max
## -2086.31 -466.49 25.62 514.24 1985.22
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 3042.380 66.571 45.701 &lt;2e-16 ***
## smokeyes -217.907 104.046 -2.094 0.0376 *
## lwt_c 5.518 2.336 2.362 0.0192 *
## smokeyes:lwt_c -2.546 3.347 -0.761 0.4479
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 700.8 on 184 degrees of freedom
## Multiple R-squared: 0.06105, Adjusted R-squared: 0.04574
## F-statistic: 3.988 on 3 and 184 DF, p-value: 0.008795</code></pre>
<p><em>From the Coefficients matrix we can see the weight of mothers who smoke are 217.9 lower than the mothers who don’t smoke. For every 1-unit increase in mother’s weight, predicted child weight goes up 5.518. The mothers who smoke their children’s weight is 2.546 lower than the children whose mothers don’t smoke</em></p>
<pre><code>- Plot the regression using `ggplot()` using geom_smooth(method=&quot;lm&quot;). If your interaction is numeric by numeric, refer to code in the slides to make the plot or check out the `interactions` package, which makes this easier. If you have 3 or more predictors, just chose two of them to plot for convenience. (10)</code></pre>
<pre class="r"><code>birthwt%&gt;%ggplot(aes(lwt_c,bwt,color = smoke))+geom_point()+geom_smooth(method = &#39;lm&#39;,se=F)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-5-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre><code>- What proportion of the variation in the outcome does your model explain? (4)</code></pre>
<p><em>From the plot we can see bwt of the mothers who don’t smoke is higher than the bwt of the mothers who smoke.</em></p>
<pre><code>- Check assumptions of linearity, normality, and homoskedasticity either graphically or using a hypothesis test (5)</code></pre>
<pre class="r"><code>library(sandwich); library(lmtest)
resids&lt;-fit$residuals
fitvals&lt;-fit$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, col=&quot;red&quot;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-6-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot()+geom_histogram(aes(resids), bins=20)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-6-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot()+geom_qq(aes(sample=resids))+geom_qq_line(aes(sample=resids))</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-6-3.png" width="768" style="display: block; margin: auto;" />
<em>From the graph inearity, homoskedasticity and normality look OK.</em></p>
<pre><code>- Regardless, recompute regression results with robust standard errors via `coeftest(..., vcov=vcovHC(...))`. Discuss significance of results, including any changes from before/after robust SEs if applicable. (10)</code></pre>
<pre class="r"><code>summary(fit)$coef[,1:2]</code></pre>
<pre><code>##                   Estimate Std. Error
## (Intercept)    3042.379791  66.571423
## smokeyes       -217.906559 104.045772
## lwt_c             5.517538   2.336399
## smokeyes:lwt_c   -2.546061   3.347337</code></pre>
<pre class="r"><code>coeftest(fit, vcov=vcovHC(fit))[,1:2] </code></pre>
<pre><code>##                   Estimate Std. Error
## (Intercept)    3042.379791  68.271797
## smokeyes       -217.906559 105.199656
## lwt_c             5.517538   2.212692
## smokeyes:lwt_c   -2.546061   3.171973</code></pre>
<p><em>Compare to normal SE, the Robust SE is higher</em></p>
<ul>
<li><strong>4. (5 pts)</strong> Rerun same regression model (with the interaction), but this time compute bootstrapped standard errors (either by resampling observations or residuals). Discuss any changes you observe in SEs and p-values using these SEs compared to the original SEs and the robust SEs)</li>
</ul>
<pre class="r"><code>temp &lt;- birthwt
samp_distn&lt;-replicate(5000, {
  boot_dat&lt;-temp[sample(nrow(temp),replace=TRUE),]
  fit&lt;-lm(bwt ~ smoke*lwt_c, data = boot_dat)
  coef(fit)
})

samp_distn%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>##   (Intercept) smokeyes    lwt_c smokeyes:lwt_c
## 1    68.03923 105.4371 2.197603       3.219327</code></pre>
<p><em>Bootstrapped standard errors is smaller than the original SEs and the robust SEs</em></p>
<ul>
<li><p><strong>5. (30 pts)</strong> Fit a logistic regression model predicting a binary variable (if you don’t have one, make/get one) from at least two explanatory variables (interaction not necessary).</p>
<ul>
<li>Interpret coefficient estimates in context (10)</li>
</ul></li>
</ul>
<pre class="r"><code>data&lt;-birthwt%&gt;%mutate(y=ifelse(ui==&quot;yes&quot;,1,0))
fit&lt;-glm(y~bwt+age, data=data, family=&quot;binomial&quot;)
coeftest(fit)</code></pre>
<pre><code>##
## z test of coefficients:
##
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) 2.56312680 1.41992894 1.8051 0.0710576 .
## bwt -0.00110426 0.00032635 -3.3836 0.0007154 ***
## age -0.05752860 0.04681449 -1.2289 0.2191232
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<p><em>bwt has a significant impact on ui and it has a negative effect</em></p>
<pre><code>- Report a confusion matrix for your logistic regression (5)</code></pre>
<pre class="r"><code>data$prob &lt;- predict(fit,type=&quot;response&quot;) 
data$predicted &lt;- ifelse(data$prob&gt;.5,&quot;yes&quot;,&quot;no&quot;) 
data$ui&lt;-factor(data$ui,levels=c(&quot;yes&quot;,&quot;no&quot;))
table(truth=data$ui, prediction=data$predicted)%&gt;%addmargins</code></pre>
<pre><code>##      prediction
## truth  no yes Sum
##   yes  26   1  27
##   no  161   0 161
##   Sum 187   1 188</code></pre>
<pre><code>- Compute and discuss the Accuracy, Sensitivity (TPR), Specificity (TNR), Precision (PPV), and AUC of your model (5)</code></pre>
<pre class="r"><code>class_diag&lt;-function(probs,truth){
  
  tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]

  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
  
  #CALCULATE EXACT AUC
  ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  
  dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  
  n &lt;- length(TPR)
  auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

  data.frame(acc,sens,spec,ppv,auc)
}

class_diag(data$prob,data$ui)</code></pre>
<pre><code>##          acc sens     spec ppv       auc
## no 0.1382979    0 0.962963   0 0.2815735</code></pre>
<pre><code>- Using ggplot, make a density plot of the log-odds (logit) colored/grouped by your binary outcome variable (5)</code></pre>
<pre class="r"><code>data$logit&lt;-predict(fit,type=&quot;link&quot;)


data%&gt;%ggplot()+geom_density(aes(logit,color=ui,fill=ui), alpha=.4)+
  theme(legend.position=c(.85,.85))+geom_vline(xintercept=0)+xlab(&quot;logit (log-odds)&quot;)+
  geom_rug(aes(logit,color=ui))+
  geom_text(x=-5,y=.07,label=&quot;TN = 431&quot;)+
  geom_text(x=-1.75,y=.008,label=&quot;FN = 19&quot;)+
  geom_text(x=1,y=.006,label=&quot;FP = 13&quot;)+
  geom_text(x=5,y=.04,label=&quot;TP = 220&quot;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-12-1.png" width="768" style="display: block; margin: auto;" />
- Generate an ROC curve (plot) and calculate AUC (either manually or with a package); interpret (5)</p>
<pre class="r"><code>sens&lt;-function(p,data=data) mean(data[data$y==1,]$prob&gt;p)
spec&lt;-function(p,data=data) mean(data[data$y==0,]$prob&lt;p)

sensitivity&lt;-sapply(seq(0,1,.01),sens,data)
specificity&lt;-sapply(seq(0,1,.01),spec,data)

ROC1&lt;-data.frame(sensitivity,specificity,cutoff=seq(0,1,.01))
ROC1$TPR&lt;-sensitivity
ROC1$FPR&lt;-1-specificity

ROC1%&gt;%ggplot(aes(FPR,TPR))+geom_path(size=1.5)+geom_segment(aes(x=0,y=0,xend=1,yend=1),lty=2)+
  scale_x_continuous(limits = c(0,1))</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-13-1.png" width="768" style="display: block; margin: auto;" />
<em>From the AUC and the ROC plot we can see it is not great. Hard to predict ui from just bwt and age!</em></p>
<ul>
<li><p><strong>6. (25 pts)</strong> Perform a logistic regression predicting the same binary response variable from <em>ALL</em> of the rest of your variables (the more, the better!)</p>
<ul>
<li>Fit model, compute in-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, AUC), and interpret (5)</li>
</ul></li>
</ul>
<pre class="r"><code>birthwt &lt;- readr::read_csv(&#39;/stor/home/cs59386/Project1/birthwt.csv&#39;)
data&lt;-birthwt%&gt;%mutate(y=ifelse(ui==&quot;yes&quot;,1,0)) %&gt;% select(-ui)
fit &lt;- glm(y~., data=data, family=&quot;binomial&quot;)
prob&lt;-predict(fit,type=&quot;response&quot;)
class_diag(prob,data$y) %&gt;% as.matrix()</code></pre>
<pre><code>##         acc      sens      spec  ppv       auc
## 1 0.8670213 0.1111111 0.9937888 0.75 0.7918104</code></pre>
<p><em>We can see AUC is fair. But we need to do the CV.</em></p>
<pre><code>- Perform 10-fold (or repeated random sub-sampling) CV with the same model and report average out-of-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, and AUC); interpret AUC and compare with the in-sample metrics (10)</code></pre>
<pre class="r"><code>set.seed(1234)
k=10

# your code here
data2 &lt;- data %&gt;% sample_frac
folds &lt;- ntile(1:nrow(data2),n=10)

diags&lt;-NULL
for(i in 1:k){
  train &lt;- data2[folds!=i,] 
  test &lt;- data2[folds==i,] 
  truth &lt;- test$y
  
  fit&lt;-glm(y~age,data=train,family=&quot;binomial&quot;)
  probs &lt;- predict(fit, newdata=test, type=&quot;response&quot;)
  
  diags&lt;-rbind(diags,class_diag(probs,truth))
}

summarize_all(diags,mean)%&gt;% as.matrix()</code></pre>
<pre><code>##            acc sens spec ppv       auc
## [1,] 0.8567251    0    1 NaN 0.5598284</code></pre>
<p><em>After doing 10-fold CV, AUC is lower. The drop in AUC from the original indicates overfitting.</em></p>
<pre><code>- Perform LASSO on the same model/variables. Choose lambda to give the simplest model whose accuracy is near that of the best (i.e., `lambda.1se`). Discuss which variables are retained. (5)</code></pre>
<pre class="r"><code>library(glmnet)
set.seed(1234)
y&lt;-as.matrix(data$y) #grab response
x&lt;-model.matrix(y~.,data=data)[,-1] #grab predictors
cv&lt;-cv.glmnet(x,y,family=&quot;binomial&quot;)
lasso&lt;-glmnet(x,y,family=&quot;binomial&quot;,lambda=cv$lambda.min)
coef(lasso)</code></pre>
<pre><code>## 11 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                           s0
## (Intercept)     1.3050469320
## age            -0.0152007314
## lwt            -0.0043900263
## raceother       .           
## racewhite       .           
## smokeyes        .           
## ptlyes          0.5860529637
## htyes          -1.2018255391
## ftvone          .           
## ftvtwo or more  .           
## bwt            -0.0008016066</code></pre>
<pre class="r"><code>lasso_dat &lt;- data %&gt;% 
  mutate(ptl= ifelse(ptl==&quot;yes&quot;, 1, 0),ht= ifelse(ht==&quot;yes&quot;, 1, 0), ) %&gt;% 
  select(age, lwt,ptl,ht,bwt,y)

fit&lt;-glm(y~.,data=lasso_dat,family=&quot;binomial&quot;)
prob&lt;-predict(fit,type=&quot;response&quot;)
class_diag(prob,lasso_dat$y) %&gt;% as.matrix()</code></pre>
<pre><code>##         acc       sens      spec       ppv       auc
## 1 0.8617021 0.07407407 0.9937888 0.6666667 0.7782379</code></pre>
<pre><code>- Perform 10-fold CV using only the variables lasso selected: compare model&#39;s out-of-sample AUC to that of your logistic regressions above (5)</code></pre>
<pre class="r"><code>set.seed(1234)
k=10

# your code here
data2 &lt;- lasso_dat %&gt;% sample_frac
folds &lt;- ntile(1:nrow(data2),n=10)

diags&lt;-NULL
for(i in 1:k){
  train &lt;- data2[folds!=i,] 
  test &lt;- data2[folds==i,] 
  truth &lt;- test$y
  
  fit&lt;-glm(y~.,data=train,family=&quot;binomial&quot;)
  probs &lt;- predict(fit, newdata=test, type=&quot;response&quot;)
  
  diags&lt;-rbind(diags,class_diag(probs,truth))
}

summarize_all(diags,mean)%&gt;% as.matrix()</code></pre>
<pre><code>##            acc       sens      spec ppv       auc
## [1,] 0.8409357 0.05833333 0.9708333 NaN 0.7256559</code></pre>
</div>
<div id="where-do-i-find-data-again" class="section level2">
<h2>Where do I find data again?</h2>
<p>You can choose ANY datasets you want that meet the above criteria for variables and observations. You can make it as serious as you want, or not, but keep in mind that you will be incorporating this project into a portfolio webpage for your final in this course, so choose something that really reflects who you are, or something that you feel will advance you in the direction you hope to move career-wise, or something that you think is really neat, or whatever. On the flip side, regardless of what you pick, you will be performing all the same tasks, so it doesn’t end up being that big of a deal.</p>
<p>If you are totally clueless and have no direction at all, log into the server and type</p>
<pre class="r"><code>data(package = .packages(all.available = TRUE))</code></pre>
<p>This will print out a list of <strong>ALL datasets in ALL packages</strong> installed on the server (a ton)! Scroll until your eyes bleed! Actually, do not scroll that much… To start with something more manageable, just run the command on your own computer, or just run <code>data()</code> to bring up the datasets in your current environment. To read more about a dataset, do <code>?packagename::datasetname</code>.</p>
<p>If it is easier for you, and in case you don’t have many packages installed, a list of R datasets from a few common packages (also downloadable in CSV format) is given at the following website: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
<ul>
<li><p>A good package to download for fun/relevant data is <code>fivethiryeight</code>.
Run <code>install.packages("fivethirtyeight"),</code> load the packages with <code>library(fivethirtyeight)</code>, run <code>data()</code>, and then scroll down to view the datasets. Here is an online list of all 127 datasets (with links to the 538 articles). Lots of sports, politics, current events, etc.</p></li>
<li><p>If you have already started to specialize (e.g., ecology, epidemiology) you might look at discipline-specific R packages (vegan, epi, respectively). We will be using some tools from these packages later in the course, but they come with lots of data too, which you can explore according to the directions above</p></li>
<li><p>However, you <em>emphatically DO NOT</em> have to use datasets available via R packages! In fact, I would much prefer it if you found the data from completely separate sources and brought them together (a much more realistic experience in the real world)! You can even reuse data from your SDS328M project, provided it shares a variable in common with other data which allows you to merge the two together (e.g., if you still had the timestamp, you could look up the weather that day: <a href="https://www.wunderground.com/history/" class="uri">https://www.wunderground.com/history/</a>). If you work in a research lab or have access to old data, you could potentially merge it with new data from your lab!</p></li>
<li><p>Here is a curated list of interesting datasets (read-only spreadsheet format): <a href="https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit" class="uri">https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit</a></p></li>
<li><p>Here is another great compilation of datasets: <a href="https://github.com/rfordatascience/tidytuesday" class="uri">https://github.com/rfordatascience/tidytuesday</a></p></li>
<li><p>Here is the UCI Machine Learning Repository: <a href="https://archive.ics.uci.edu/ml/index.php" class="uri">https://archive.ics.uci.edu/ml/index.php</a></p>
<ul>
<li>See also <a href="https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data" class="uri">https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data</a></li>
</ul></li>
<li><p>Here is another good general place to look: <a href="https://www.kaggle.com/datasets" class="uri">https://www.kaggle.com/datasets</a></p></li>
<li><p>To help narrow your search down or to see interesting variable ideas, check out <a href="https://www.tylervigen.com/spurious-correlations" class="uri">https://www.tylervigen.com/spurious-correlations</a>. This is the spurious correlations website, and it is fun, but if you look at the bottom of each plot you will see sources for the data. This is a good place to find very general data (or at least get a sense of where you can scrape data together from)!</p></li>
<li><p>If you are interested in medical data, check out www.countyhealthrankings.org</p></li>
<li><p>If you are interested in scraping UT data, they make <em>loads</em> of data public (e.g., beyond just professor CVs and syllabi). Check out all the data that is available in the statistical handbooks: <a href="https://reports.utexas.edu/statistical-handbook" class="uri">https://reports.utexas.edu/statistical-handbook</a></p></li>
</ul>
<div id="broader-data-sources" class="section level5">
<h5>Broader data sources:</h5>
<p><a href="www.data.gov">Data.gov</a> 186,000+ datasets!</p>
<p><a href="Social%20Explorer">Social Explorer</a> is a nice interface to Census and American Community Survey data (more user-friendly than the government sites). May need to sign up for a free trial.</p>
<p><a href="www.bls.gov">U.S. Bureau of Labor Statistics</a></p>
<p><a href="www.census.gov">U.S. Census Bureau</a></p>
<p><a href="www.gapminder.org/data">Gapminder</a>, data about the world.</p>
<p>…</p>
</div>
</div>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
